# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: Apache-2.0
"""Unit precondition for the block naming the cases a test module holds.

Covers `MQC_CMN_UNI_112348`, inventoried in
``docs/design/cmn_verdict_and_cli.md`` section 10.

**Split from `mqc_uni_file_standards.py` on 2026-10-08**, which this subject
took to 960 lines against the nine-hundred-line runway ceiling. That module is
about what a Python file must satisfy; this one is about a generated block
agreeing with the module it sits in.

A failure here is **not a model finding**, so the module carries no priority
marker, per ``framework-rules.md`` section 3.3.
"""

# ------------------------------------------------------------- cases in here
# Generated by `tools/refresh_case_summaries.py`.
#
# TestMQCCaseSummaries
#   112348  a_case_block_disagreeing_with_its_module_is_reported
# ------------------------------------------------------------ end of cases

from pathlib import Path

import pytest

from cmn.case_summary import (
    block_delimiters,
    refreshed_source,
    summary_problems,
)

pytestmark = pytest.mark.unit


class TestMQCCaseSummaries:
    """Each test module's block names the cases it actually holds."""

    def MQC_CMN_UNI_112348_a_case_block_disagreeing_with_its_module_is_reported(
        self, tmp_path: Path
    ) -> None:
        """Generated from the module's own cases, and compared both ways.

        **Neither direction is fixable by editing the block.** A case added
        without refreshing fails here, and a block naming a deleted case fails
        here too; the remedy for both is one command.

        Design: ``testing-standards.md``, "A Test Module Lists The Cases It
        Holds".

        Returns:
            None
        """
        root = Path(__file__).resolve().parents[2]
        problems = summary_problems(root)
        assert not problems, (
            f"{len(problems)} module(s) carry a case block that disagrees with "
            f"the cases they define: " + "; ".join(problems)
        )

        # AND THE CHECK IS NOT VACUOUS, which a passing suite cannot establish
        # on its own. A module with a case and no block is reported, a block
        # with no case is reported, and a block naming the wrong case is too.
        opening, closing = block_delimiters()
        module = tmp_path / "tests" / "cmn" / "mqc_uni_probe.py"
        module.parent.mkdir(parents=True)
        body = (
            '"""A probe."""\n\n\nclass TestMQCProbe:\n'
            '    """One case."""\n\n'
            "    def MQC_CMN_UNI_119000_a_probe(self) -> None:\n"
            '        """Do nothing.\n\n        Returns:\n            None\n'
            '        """\n'
        )
        module.write_text(body, encoding="utf-8", newline="\n")
        missing = summary_problems(tmp_path)
        assert len(missing) == 1 and "carries no case block" in missing[0], missing

        module.write_text(
            refreshed_source(module), encoding="utf-8", newline="\n"
        )
        assert not summary_problems(tmp_path), "a refreshed module still reported"

        # THE BLOCK NAMES THE CASE AND ITS CLASS, in the delimiters the tool
        # writes rather than in a copy of them.
        written = module.read_text(encoding="utf-8")
        assert opening in written and closing in written
        assert "#   119000  a_probe" in written, written
        assert "# TestMQCProbe" in written, written

        # A CASE ADDED WITHOUT REFRESHING IS REPORTED.
        module.write_text(
            written.replace(
                "    def MQC_CMN_UNI_119000_a_probe(self) -> None:",
                "    def MQC_CMN_UNI_119001_a_second(self) -> None:\n"
                '        """Do nothing.\n\n        Returns:\n            None\n'
                '        """\n\n'
                "    def MQC_CMN_UNI_119000_a_probe(self) -> None:",
                1,
            ),
            encoding="utf-8",
            newline="\n",
        )
        stale = summary_problems(tmp_path)
        assert len(stale) == 1 and "disagrees with" in stale[0], stale

        # A BLOCK IN A MODULE THAT DEFINES NO CASE IS REPORTED, which is the
        # direction a generator alone would never produce and a deletion does.
        empty = tmp_path / "tests" / "cmn" / "mqc_uni_empty.py"
        empty.write_text(
            f'"""A module with no case."""\n\n{opening}\n{closing}\n',
            encoding="utf-8",
            newline="\n",
        )
        orphaned = [
            problem for problem in summary_problems(tmp_path)
            if "mqc_uni_empty" in problem
        ]
        assert len(orphaned) == 1 and "defines no case" in orphaned[0], orphaned
