# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: Apache-2.0
"""Unit preconditions for what this project declares it depends on and ships.

Covers `MQC_CMN_UNI_112222` through `112225` and `112231`, inventoried in
``docs/design/cmn_verdict_and_cli.md`` section 10.

**Split from `mqc_uni_metadata.py` on 2026-10-08**, which the generated case
block took to 1016 lines against the thousand-line hard ceiling. That module
had been declared past the nine-hundred-line runway since 2026-10-05, and a
declaration states the next subject moves out: this is that subject.

**The two subjects were never related.** One is about what a result record
carries; this one is about the requirements files, the pinned gating tools, the
imports that must be declared and the packages the build must configure. A
failure here means the project cannot be installed as described rather than
that a measurement was recorded wrongly.

A failure here is **not a model finding**, so the module carries no priority
marker, per ``framework-rules.md`` section 3.3.
"""

# ------------------------------------------------------------- cases in here
# Generated by `tools/refresh_case_summaries.py`.
#
# TestMQCDependencyDeclaration
#   112222  requirements_files_disagreeing_with_pyproject_fail
#   112231  an_installed_gating_tool_outside_its_pin_is_reported
#   112223  every_imported_package_is_declared
#   112224  random_test_ordering_is_declared
# TestMQCPackaging
#   112225  every_package_on_disk_is_configured_for_the_build
# ------------------------------------------------------------ end of cases

import ast
import re
import sys
import tomllib
from importlib import metadata
from pathlib import Path

import pytest
from packaging.specifiers import SpecifierSet

from tools.generate_requirements import generate, read_declaration

from tests.cmn.metadata_support import requirement_name

pytestmark = pytest.mark.unit

# Trees that are not this project's source. Named here rather than imported,
# because the one in `cmn.code_standards` serves the code standards and this
# one serves a package listing: the two answer different questions and have
# drifted apart before.
_SKIPPED_TREES = frozenset({"venv", ".venv", "build", "dist", "__pycache__"})


class TestMQCDependencyDeclaration:
    """One declaration, and a check on every copy derived from it."""

    def MQC_CMN_UNI_112222_requirements_files_disagreeing_with_pyproject_fail(self) -> None:
        """The generated files are a convenience, never a second source of truth.

        Without this they are a second declaration, and a second declaration
        drifts. That is the rule applied everywhere else here: either there is
        one statement of a fact, or there is a check.

        The case reads the declaration and regenerates, rather than comparing
        the two files to each other. Comparing copies would pass while both
        were stale.

        Returns:
            None
        """
        root = Path(__file__).resolve().parents[2]
        for path, expected in generate(root).items():
            assert path.is_file(), f"{path.name} has not been generated"
            assert path.read_text(encoding="utf-8") == expected, (
                f"{path.name} disagrees with pyproject.toml; regenerate it with "
                f"python tools/generate_requirements.py"
            )

    def MQC_CMN_UNI_112231_an_installed_gating_tool_outside_its_pin_is_reported(
        self,
    ) -> None:
        """A local pylint outside the pin reports a different result from CI.

        **This case exists because it happened.** `pyproject.toml` pins
        `pylint>=3.3,<4.0` and 4.0.6 was installed locally. Gate 1 exited 0
        here and 8 in CI, on the same commit, because the newer pylint counts
        `self` differently against `max-args`. Two commits were pushed on the
        strength of a local run that was measuring a different tool.

        **`112222` cannot catch this.** It compares the generated requirements
        files against `pyproject.toml`, so it verifies what is *declared* agrees
        with itself. Nothing verified what is *installed* agrees with the
        declaration, and the declaration is what CI installs from.

        **Scoped to the tools that gate**, which is pylint and pytest. A drifting
        library changes behaviour and the suite says so; a drifting linter or
        runner changes the verdict on every other case at once, silently.

        Returns:
            None
        """
        root = Path(__file__).resolve().parents[2]
        _, development = read_declaration(root / "pyproject.toml")
        pinned = {
            name.lower(): spec
            for name, spec in (
                (requirement_name(entry), entry) for entry in development
            )
            if name is not None
        }

        wrong: list[str] = []
        for tool in ("pylint", "pytest"):
            spec = pinned.get(tool)
            if spec is None:
                wrong.append(f"{tool} gates a CI step and is not pinned at all")
                continue
            installed = metadata.version(tool)
            if not SpecifierSet(spec[len(tool):]).contains(installed, prereleases=True):
                wrong.append(f"{tool} {installed} is installed against the pin {spec}")

        assert not wrong, (
            "the installed toolchain does not satisfy what CI installs from, so a "
            f"local gate result does not predict the CI one: {wrong}. Run "
            f"`python -m pip install --editable \".[dev]\"` to align them"
        )

    def MQC_CMN_UNI_112223_every_imported_package_is_declared(self) -> None:
        """A dependency the code imports and nothing declares breaks a clean install.

        It passes on the machine that happens to have it and fails on every
        other, which makes the failure a property of the environment rather
        than of the change that introduced it.

        Returns:
            None
        """
        root = Path(__file__).resolve().parents[2]
        runtime, development = read_declaration(root / "pyproject.toml")
        declared = {
            re.split(r"[<>=!\[]", entry)[0].strip().lower().replace("-", "_")
            for entry in runtime + development
        }
        # The import name and the distribution name differ for these, which is
        # exactly the kind of mapping a check has to state rather than infer.
        aliases = {
            "yaml": "pyyaml",
            "google": "google_genai",
            # `allure` is shipped by allure-python-commons, which
            # allure-pytest depends on and does not provide.
            "allure": "allure_python_commons",
        }

        # Parsed, not pattern-matched. A regex over source lines also matches
        # prose: a docstring line beginning "from the artifact alone" reads as
        # an import of a package named "the". The parser knows the difference.
        imported = set()
        for source in root.rglob("*.py"):
            if any(part in {"venv", ".venv", "build", "dist"} for part in source.parts):
                continue
            for node in ast.walk(ast.parse(source.read_text(encoding="utf-8"))):
                if isinstance(node, ast.Import):
                    imported.update(alias.name.split(".")[0] for alias in node.names)
                elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                    imported.add(node.module.split(".")[0])

        local = {"ingestion", "execution", "evaluation", "cmn", "tests", "conftest", "tools"}
        third_party = {
            aliases.get(name, name) for name in imported
            if name not in sys.stdlib_module_names and name not in local
        }
        assert third_party <= declared, (
            f"imported and undeclared: {sorted(third_party - declared)}"
        )

    def MQC_CMN_UNI_112224_random_test_ordering_is_declared(self) -> None:
        """The suite depends on shuffled order for a guarantee it would else lack.

        The extension cases register a layer, an outcome and a verdict rule and
        then remove each one. A cleanup that failed would change the
        distribution denominator for every case running afterwards, and the
        failure would land on whichever case happened to run last.

        Found installed locally and declared nowhere, which is the worse of the
        two arrangements: **local runs held a guarantee CI did not**, so CI was
        the weaker check while appearing to be the stronger one.

        Returns:
            None
        """
        root = Path(__file__).resolve().parents[2]
        _, development = read_declaration(root / "pyproject.toml")
        assert any(entry.startswith("pytest-randomly") for entry in development)


class TestMQCPackaging:
    """What a consumer installs must be what is on disk."""

    def MQC_CMN_UNI_112225_every_package_on_disk_is_configured_for_the_build(self) -> None:
        """A package the build drops fails every consumer on its first import.

        **A hand-written list shipped a broken distribution.** It named four
        packages and omitted ``execution.adapters``, so the wheel held
        ``execution/`` with no adapters in it. The registry imports all three
        adapters at import time, so nothing that installed it could start.

        Nothing here detected that, because the repository is normally used from
        its own source tree where the directories are simply present and the
        build configuration is never exercised. It surfaced the first time this
        repository was installed into another one.

        Returns:
            None
        """
        root = Path(__file__).resolve().parents[2]
        configured = tomllib.loads(
            (root / "pyproject.toml").read_text(encoding="utf-8")
        )["tool"]["setuptools"]["packages"]["find"]
        patterns = [entry.rstrip("*") for entry in configured["include"]]
        excluded = [entry.rstrip("*") for entry in configured["exclude"]]

        on_disk = {
            path.parent.relative_to(root).as_posix()
            for path in root.rglob("__init__.py")
            if not any(part in _SKIPPED_TREES for part in path.parts)
        }

        unshipped = [
            package for package in sorted(on_disk)
            if not any(package.startswith(prefix) for prefix in patterns)
            and not any(package.startswith(prefix) for prefix in excluded)
        ]
        assert not unshipped, (
            f"packages on disk that the build would not ship: {unshipped}. "
            f"Add a matching include pattern to pyproject.toml."
        )

        # The subpackage the omission actually dropped, named so a regression
        # reports the real case rather than only a general rule.
        assert "execution/adapters" in on_disk
        assert any("execution".startswith(prefix.rstrip("/")) for prefix in patterns)
