# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: Apache-2.0
"""Unit preconditions for result emission, the code registry and the fixtures.

Covers `MQC_CMN_UNI_112200` through `112203`, `112204`, `112119` through `112208`,
`112209` through `112211`, `10171` through `10173`, `112213`, `112214` and `112215`
through `112218`, inventoried in ``docs/design/cmn_verdict_and_cli.md``
section 10.

**Run-scoped fields are emitted twice**, once in a manifest and again on every
result, because collectors key on per-test rows and a field living only in a
manifest may never reach per-test history.

**The excerpt guards are preconditions, not graded cases.** An excerpt silently
corrected by a formatter would leave every graded case built on it asserting
against an expectation that no longer holds, and the failure would be a
confident wrong verdict rather than an error. A stale fixture is an
instrument defect.

A failure here is **not a model finding**, so the module carries no priority marker, per
``framework-rules.md`` section 3.3.
"""

# ------------------------------------------------------------- cases in here
# Generated by `tools/refresh_case_summaries.py`.
#
# TestMQCTaxonomyRegistryConsistency
#   112200  emitted_code_absent_from_registry_is_rejected
#   112201  registered_code_with_no_emit_site_is_reported
#   112202  unregistered_code_in_a_live_specification_is_reported
#   112203  stated_inventory_counts_disagreeing_with_rows_is_reported
# TestMQCResultEmission
#   112205  run_scoped_fields_emitted_per_result_not_in_a_manifest_alone
#   112204  run_context_and_gated_flag_recorded_in_metadata
#   112208  result_missing_a_required_metadata_field_is_rejected
#   112209  selection_mode_recorded_per_result
#   112218  result_records_the_platform_it_ran_on
#   112215  graded_result_records_its_evaluation_family
#   112217  precondition_result_carries_no_family
#   112216  unregistered_family_value_is_rejected
# TestMQCLatencyStatistics
#   112207  truncated_duration_excluded_from_latency_statistics
#   112219  latency_is_absent_rather_than_zero_when_nothing_measured
# TestMQCArtifactSeparation
#   112210  debug_artifact_name_does_not_match_collector_pattern
#   112211  debug_rows_carry_ci_debug_context_and_ungated_flag
# TestMQCDiagnosticSummary
#   112213  summary_records_job_run_number_both_refs_and_changed_areas
#   112214  fixture_ref_defaults_to_code_ref_when_not_supplied
#   112220  changed_areas_distinguish_harness_from_tests
#   112212  first_run_on_a_branch_has_no_previous_conclusion_to_compare
# TestMQCObservationAssembly
#   112206  observation_assembled_from_tier_results_and_case_metadata
#   112221  a_field_the_record_does_not_declare_is_rejected
# TestMQCFindingDirections
#   112227  invention_and_omission_are_both_registered_codes
# TestMQCFamilyRegistrationMechanism
#   112228  family_table_disagreeing_with_the_code_registry_is_reported
#   112229  every_requirement_in_the_matrix_appears_in_the_plan
#   112230  a_registered_family_without_ground_truth_is_reported
# TestMQCInventoryIdentifiers
#   112226  an_identifier_appearing_twice_in_one_inventory_is_reported
# ------------------------------------------------------------ end of cases

import csv
import re
from pathlib import Path
from typing import Any

import pytest

from cmn.code_standards import section_lines
from cmn.metadata import (
    DiagnosticSummary,
    artifact_name,
    changed_areas_from,
    current_platform,
    emit_result,
    latency_statistics,
    matches_collector_pattern,
    require_registered_code,
    unemitted_codes,
)
from cmn.observations import (
    Observation,
    RunContext,
    assemble_observation,
    required_result_fields,
)
from cmn.registries import (
    evaluation_family,
    registered_codes,
    registered_evaluation_families,
)

from tests.cmn.metadata_support import graded_observation


pytestmark = pytest.mark.unit

# A taxonomy code as a design document writes one.
_CODE_PATTERN = re.compile(r"`(QC_(?:LLM|SEC|HARNESS|DATA)_[A-Z_]+)`")
# One row of the evaluation family table in harness_test_taxonomy.md section 11.1.
# Parsed rather than substring-matched: the surrounding prose names these
# identifiers too, and reporting prose would be the over-reporting that trains
# a check away on its second run.
# A harness requirement identifier, as the plan and the matrix both write one.
# Requirements carry an explicit MQC_REQ_ marker, so an identifier says which
# register it belongs to without the reader knowing any vocabulary.
# harness_test_plan.md section 2.2.
_REQUIREMENT_ID = re.compile(r"MQC_REQ_HAR_(?:ING|EXE|EVL|CMN)_\d+")


_FAMILY_ROW = re.compile(
    r"^\|\s*`(?P<identifier>[a-z][a-z_]+)`\s*\|[^|]+\|[^|]+\|[^|]+\|$"
)

# One inventory row: an identifier, a category letter and a behaviour name.
# Parsed rather than substring-matched, because prose naming an identifier is
# not a row and reporting it would be the over-reporting that trains a check
# away on its second run.
_INVENTORY_ROW = re.compile(
    r"^\|\s*`(?P<identifier>\d{6})`\s*\|\s*[PNB]\s*\|\s*`(?P<behaviour>\w+)`\s*\|$"
)


# Dated records rather than live specifications. The Phase 0 register
# deliberately names alternatives that were considered and rejected, so a code
# appearing there is evidence of a decision rather than an unregistered entry.
_HISTORICAL_DOCUMENTS = frozenset({"harness_phase0_project_ambiguities.md"})

# Directories that are not this project's source, so their conventions are
# not this project's to enforce.

# The identifier this repository's files must declare. The case repository
# runs the same check against MIT, which is the whole point of naming it
# rather than accepting any SPDX tag.
_REPOSITORY_LICENCE = "Apache-2.0"


@pytest.fixture(name="gated_run")
def fixture_gated_run() -> RunContext:
    """Return a gated CI run context.

    Returns:
        RunContext: A full, gated CI run.
    """
    return RunContext(
        run_context="ci", selection_mode="full", preconditions_executed=True,
        rule_set_hash="sha256:abc", effective_thresholds={"pass_floor": 0.9},
        timeout_ms=60000, cli_flags={"judge_on_failure": False},
        platform="linux",
    )


class TestMQCTaxonomyRegistryConsistency:
    """Every emitted code registered, and every registered code accounted for."""

    def MQC_CMN_UNI_112200_emitted_code_absent_from_registry_is_rejected(self) -> None:
        """An unregistered code makes the record uncountable.

        Every later tally by root-cause class would silently omit it, and a
        count that silently omits is worse than one that fails.

        Returns:
            None
        """
        with pytest.raises(ValueError, match="QC_HARNESS_PARSER_ERROR"):
            require_registered_code("QC_LLM_INVENTED_HERE")
        assert require_registered_code("QC_LLM_RUBRIC_FAILURE") == "QC_LLM_RUBRIC_FAILURE"

    def MQC_CMN_UNI_112201_registered_code_with_no_emit_site_is_reported(self) -> None:
        """A code registered and never emitted is dead or forgotten.

        Reported rather than failed: both are worth knowing and neither means
        the run was wrong.

        Returns:
            None
        """
        emitted = ["QC_LLM_RUBRIC_FAILURE", "QC_SEC_JUDGE_HIJACK"]
        unemitted = unemitted_codes(emitted)

        assert "QC_HARNESS_AUTH_ERROR" in unemitted
        assert "QC_LLM_RUBRIC_FAILURE" not in unemitted
        assert len(unemitted) == len(registered_codes()) - 2

    def MQC_CMN_UNI_112202_unregistered_code_in_a_live_specification_is_reported(self) -> None:
        """Every code a design document names must exist in the registry.

        The single registry is only single if nothing else declares one, and a
        design naming a code that does not exist would have an implementation
        invent it.

        Returns:
            None
        """
        design_dir = Path(__file__).resolve().parents[2] / "docs" / "design"
        named: set[str] = set()
        for document in design_dir.glob("*.md"):
            if document.name in _HISTORICAL_DOCUMENTS:
                continue
            for line in document.read_text(encoding="utf-8").splitlines():
                if line.lstrip().startswith("|"):
                    named |= set(_CODE_PATTERN.findall(line))

        assert named
        assert named <= registered_codes()

    def MQC_CMN_UNI_112203_stated_inventory_counts_disagreeing_with_rows_is_reported(self) -> None:
        """A stated total is derived data, and derived data can be restated wrongly.

        Returns:
            None
        """
        design_dir = Path(__file__).resolve().parents[2] / "docs" / "design"
        checked = 0
        for document in design_dir.glob("*.md"):
            text = document.read_text(encoding="utf-8")
            stated = re.search(
                r"\*\*Inventory: (\d+) cases, (\d+) negative, (\d+) positive, "
                r"(\d+) boundary", text
            )
            if stated is None:
                continue
            categories = re.findall(r"^\| `\d{6}` \| ([PNB]) \|", text, re.M)
            assert int(stated.group(1)) == len(categories), document.name
            assert int(stated.group(2)) == categories.count("N"), document.name
            assert int(stated.group(3)) == categories.count("P"), document.name
            assert int(stated.group(4)) == categories.count("B"), document.name
            checked += 1
        assert checked == 4


class TestMQCResultEmission:
    """What every emitted result carries, and what it is refused for lacking."""

    def MQC_CMN_UNI_112205_run_scoped_fields_emitted_per_result_not_in_a_manifest_alone(
        self, gated_run: RunContext
    ) -> None:
        """Collectors key on per-test rows.

        A field living only in a run manifest may never reach per-test history,
        and a stored result whose thresholds cannot be recovered is
        uninterpretable years later. Repeating seven fields costs nothing
        measurable.

        Args:
            gated_run (RunContext): The run-scoped fields.

        Returns:
            None
        """
        emitted = emit_result(graded_observation(), gated_run)

        assert emitted["effective_thresholds"] == {"pass_floor": 0.9}
        assert emitted["rule_set_hash"] == "sha256:abc"
        assert emitted["timeout_ms"] == 60000
        assert emitted["cli_flags"] == {"judge_on_failure": False}

    def MQC_CMN_UNI_112204_run_context_and_gated_flag_recorded_in_metadata(
        self, gated_run: RunContext
    ) -> None:
        """Row marking is one of the two mechanisms excluding a debug run.

        Args:
            gated_run (RunContext): The run-scoped fields.

        Returns:
            None
        """
        emitted = emit_result(graded_observation(), gated_run)
        assert emitted["run_context"] == "ci"
        assert emitted["gated"] is True

        debug = RunContext(
            run_context="ci_debug", selection_mode="full", preconditions_executed=True
        )
        assert emit_result(graded_observation(), debug)["gated"] is False

    def MQC_CMN_UNI_112208_result_missing_a_required_metadata_field_is_rejected(self) -> None:
        """A result that reaches the record incomplete is uninterpretable later.

        It also looks exactly like one that is not, which is why the refusal
        happens at emission rather than at read.

        Returns:
            None
        """
        from cmn.observations import (  # pylint: disable=import-outside-toplevel
            require_complete_result,
        )

        with pytest.raises(ValueError, match="QC_HARNESS_PARSER_ERROR") as caught:
            require_complete_result({"case_id": "MQC_TASK_a::MQC_RULE_r"})
        assert "layer" in str(caught.value)
        assert set(required_result_fields()) >= {"case_id", "layer", "outcome"}

    def MQC_CMN_UNI_112209_selection_mode_recorded_per_result(self, gated_run: RunContext) -> None:
        """A reader of one row can tell how much of the suite it came from.

        Args:
            gated_run (RunContext): The run-scoped fields.

        Returns:
            None
        """
        assert emit_result(graded_observation(), gated_run)["selection_mode"] == "full"

    def MQC_CMN_UNI_112218_result_records_the_platform_it_ran_on(
        self,
        gated_run: RunContext,
    ) -> None:
        """The harness is verified on two platforms (A18).

        A result that does not say which produced it cannot support the
        comparison that verification exists to make.

        Args:
            gated_run (RunContext): The run-scoped fields.

        Returns:
            None
        """
        assert emit_result(graded_observation(), gated_run)["os"] == "linux"
        assert current_platform() in {"windows", "linux", "darwin"}

    def MQC_CMN_UNI_112215_graded_result_records_its_evaluation_family(
        self,
        gated_run: RunContext,
    ) -> None:
        """Coverage is read per family, not only per requirement.

        A requirement covered by three families has survived a change of
        domain; one covered by a single family has been observed once, in one
        setting, and may hold only there.

        Args:
            gated_run (RunContext): The run-scoped fields.

        Returns:
            None
        """
        emitted = emit_result(graded_observation(families=("code_comprehension",)), gated_run)
        assert emitted["families"] == ["code_comprehension"]
        assert emitted["primary_family"] == "code_comprehension"
        assert "code_comprehension" in registered_evaluation_families()

    def MQC_CMN_UNI_112217_precondition_result_carries_no_family(
        self,
        gated_run: RunContext,
    ) -> None:
        """A precondition tests the harness, which performs no task.

        The boundary is stated rather than left implicit, because an empty
        string and an absent value read differently to a collector.

        Args:
            gated_run (RunContext): The run-scoped fields.

        Returns:
            None
        """
        precondition = Observation("MQC_TASK_pre::MQC_RULE_pre", "UNI", "pass")
        assert not emit_result(precondition, gated_run)["families"]
        assert emit_result(precondition, gated_run)["primary_family"] is None

    def MQC_CMN_UNI_112216_unregistered_family_value_is_rejected(self) -> None:
        """Families are a registry, and an unregistered value is untraceable.

        **Rejected on the record rather than merely absent from the registry.**
        Until 2026-10-03 this asserted registry membership, which establishes
        that the lookup works and not that anything consults it; the per-value
        check in section 11.7.2 is what it has to reach.

        Returns:
            None
        """
        assert "invented_family" not in registered_evaluation_families()
        with pytest.raises(ValueError, match="are not registered"):
            graded_observation(families=("invented_family",))


class TestMQCLatencyStatistics:
    """What a duration may contribute to, and what it may not."""

    def MQC_CMN_UNI_112207_truncated_duration_excluded_from_latency_statistics(self) -> None:
        """A truncated duration measures the harness's patience.

        A case that timed out at the configured ceiling would drag its own
        baseline upward, making genuinely slow responses look normal
        afterwards, which is the opposite of what a baseline is for.

        Returns:
            None
        """
        observations = [
            graded_observation(duration=100), graded_observation(duration=200),
            graded_observation(duration=60000, duration_kind="truncated"),
        ]
        statistics = latency_statistics(observations)

        assert statistics["mean_duration"] == pytest.approx(150.0)
        assert statistics["sample_count"] == 2
        assert statistics["excluded_truncated"] == 1

    def MQC_CMN_UNI_112219_latency_is_absent_rather_than_zero_when_nothing_measured(self) -> None:
        """A mean of zero would read as an impossibly fast run.

        Returns:
            None
        """
        statistics = latency_statistics(
            [graded_observation(duration=60000, duration_kind="truncated")]
        )
        assert statistics["mean_duration"] is None
        assert statistics["sample_count"] == 0


class TestMQCArtifactSeparation:
    """Two independent mechanisms keeping a debug run out of the record."""

    def MQC_CMN_UNI_112210_debug_artifact_name_does_not_match_collector_pattern(self) -> None:
        """Structural separation, the first of the two mechanisms.

        Marking alone fails if nobody filters on it, and structural separation
        alone fails the day someone widens the pattern. Both exist because
        either one is a single point of failure.

        Returns:
            None
        """
        debug = RunContext("ci_debug", "full", True)
        gated = RunContext("ci", "full", True)

        assert matches_collector_pattern(artifact_name(gated)) is True
        assert matches_collector_pattern(artifact_name(debug)) is False

        # THE LITERAL PREFIX, which the pattern check alone does not pin: both
        # prefixes renamed together would satisfy the two assertions above.
        # Absorbed from a second callable that duplicated this identifier,
        # design section 10.10.1.
        assert artifact_name(debug).startswith("diagnostic-local")
        assert not matches_collector_pattern(artifact_name(debug, suffix="ubuntu"))

    def MQC_CMN_UNI_112211_debug_rows_carry_ci_debug_context_and_ungated_flag(self) -> None:
        """Row marking, the second mechanism, on every row rather than once.

        Returns:
            None
        """
        debug = RunContext("ci_debug", "full", True)
        fields = debug.as_fields()

        assert fields["run_context"] == "ci_debug"
        assert fields["gated"] is False

class TestMQCDiagnosticSummary:
    """What a debug summary says, starting with what the run is not."""

    def MQC_CMN_UNI_112213_summary_records_job_run_number_both_refs_and_changed_areas(
        self,
    ) -> None:
        """A notification is worthless if the reader cannot identify the run.

        It has to be findable again a week later from the notification alone,
        which is why the run number and identifier are both there.

        Returns:
            None
        """
        summary = DiagnosticSummary(
            workflow="debug-branch-on-demand", job="graded", run_number=412,
            run_id="18273645", code_ref="a1b2c3d", fixture_ref="e4f5g6h",
            changed_areas="both", mode="replay", engine="gemini",
            selection_mode="manual", case_count=12,
            resolved_models={"gemini": "gemini-flash-002"},
        )
        rendered = summary.render()

        assert rendered.startswith("This run is diagnostic.")
        assert "carries no verdict and gates nothing" in rendered
        assert "412" in rendered and "18273645" in rendered
        assert "a1b2c3d" in rendered and "e4f5g6h" in rendered
        assert "Changed areas: both" in rendered
        assert "gemini-flash-002" in rendered
        assert summary.refs_diverge is True

    def MQC_CMN_UNI_112214_fixture_ref_defaults_to_code_ref_when_not_supplied(self) -> None:
        """The boundary: equal is the ordinary case, and empty is not the same.

        An empty value would read as unknown rather than as the same, and the
        two mean very different things to a checkpoint comparison.

        Returns:
            None
        """
        summary = DiagnosticSummary(
            workflow="debug-branch-on-demand", job="graded", run_number=1,
            run_id="1", code_ref="a1b2c3d", changed_areas="harness",
            mode="replay", engine="gemini", selection_mode="full", case_count=3,
        )
        assert summary.fixture_ref == "a1b2c3d"
        assert summary.refs_diverge is False

    @pytest.mark.parametrize(
        "paths,expected",
        [
            (["execution/dispatch.py"], "harness"),
            (["tests/cmn/mqc_uni_verdict.py"], "tests"),
            (["cmn/verdict.py", "tests/cmn/mqc_uni_verdict.py"], "both"),
            (["docs/design/tier2_execution.md"], "none"),
        ],
    )
    def MQC_CMN_UNI_112220_changed_areas_distinguish_harness_from_tests(
        self, paths: list[str], expected: Any
    ) -> None:
        """A run where only tests changed and results moved points at the tests.

        Reporting a single undifferentiated diff leaves the reader to work that
        out from paths, which is exactly the work the summary exists to save.

        Args:
            paths (list): The changed paths.
            expected (str): The classification.

        Returns:
            None
        """
        assert changed_areas_from(paths) == expected

    def MQC_CMN_UNI_112212_first_run_on_a_branch_has_no_previous_conclusion_to_compare(
        self,
    ) -> None:
        """The boundary: nothing to compare is not the same as no change.

        A first run reporting "status unchanged" would be stating a comparison
        it never made.

        Returns:
            None
        """
        previous_conclusion = None
        current = "success"

        assert previous_conclusion is None
        changed = previous_conclusion is not None and previous_conclusion != current
        assert changed is False
        assert (previous_conclusion == current) is False


class TestMQCObservationAssembly:
    """Neither half of an observation is sufficient on its own."""

    def MQC_CMN_UNI_112206_observation_assembled_from_tier_results_and_case_metadata(
        self,
    ) -> None:
        """Tier 3 never receives priority, so it cannot produce a complete record.

        The orchestrating test holds the case metadata and has no access to what
        dispatch measured; the tiers hold the measurement and are deliberately
        denied the grading metadata. The reporting hook is where the two meet,
        which is why assembly is its own operation rather than a tier's job.

        Returns:
            None
        """
        case_metadata = {
            "case_id": "MQC_TASK_a::MQC_RULE_r", "layer": "EVAL", "priority": 1,
            "priority_conditions": ["P1_ATTRIBUTION"],
            "families": ("requirement_match",),
            "requirement_ids": ["MQC_REQ_MDL_GND_0001"],
        }
        tier_results = {
            "outcome": "pass", "engine": "gemini", "mode": "replay",
            "requested_model": "gemini-flash-latest",
            "resolved_model": "gemini-flash-002",
            "duration": 310, "duration_kind": "measured", "output_tokens": 42,
            "score": 4.0, "scale_id": "continuous_1_5", "rubric_result": "evaluated",
        }
        assembled = assemble_observation(case_metadata, tier_results)

        assert assembled.priority == 1
        assert assembled.resolved_model == "gemini-flash-002"
        assert assembled.score == 4.0
        assert assembled.graded is True

    def MQC_CMN_UNI_112221_a_field_the_record_does_not_declare_is_rejected(self) -> None:
        """A field nothing reads would reach the artifact unread.

        Silently dropping it would be worse: a caller believing it recorded
        something would have recorded nothing, and nothing would say so.

        Returns:
            None
        """
        with pytest.raises(ValueError, match="QC_HARNESS_PARSER_ERROR") as caught:
            assemble_observation(
                {"case_id": "MQC_TASK_a::MQC_RULE_r", "layer": "UNI"},
                {"outcome": "pass", "reviewer_note": "looks fine"},
            )
        assert "reviewer_note" in str(caught.value)






class TestMQCFindingDirections:
    """The taxonomy carries both directions of a finding."""

    def MQC_CMN_UNI_112227_invention_and_omission_are_both_registered_codes(
        self,
    ) -> None:
        """A recall figure needs both directions to mean anything.

        A model that reports every defect and several that do not exist scores
        identically to one that reports none, unless invention and omission are
        counted separately. The ``code_comprehension`` family measures recall
        over a fixed set of known defects, so the registry has to carry a code
        for each direction or the measurement collapses.

        **Deliberately weak on its own.** What it protects is a design property
        that a single deletion would silently break: ``112201`` reports an
        unemitted code without failing, and no case is written against a code
        that no longer exists.

        Returns:
            None
        """
        registered = registered_codes()
        pairs = (
            # Invention against alteration: content invented, content changed.
            ("QC_LLM_UNSOURCED_CLAIM", "QC_LLM_SOURCE_ALTERATION"),
            # Invention against omission, at the level of a finding.
            ("QC_LLM_HALLUCINATION", "QC_LLM_DEFECT_MISSED"),
        )

        for invention, counterpart in pairs:
            assert invention in registered, (
                f"{invention} is half of a documented pair and is missing"
            )
            assert counterpart in registered, (
                f"{counterpart} is the other half of {invention} and is missing; "
                f"a recall figure over one direction alone means nothing"
            )

        # The matching family reads its inputs correctly and applies the wrong
        # rule to them, which no other registered code describes.
        assert "QC_LLM_MATCH_MISCOMPUTED" in registered


class TestMQCFamilyRegistrationMechanism:
    """Section 11.2 is a procedure; these are the parts of it that are checked."""

    def MQC_CMN_UNI_112228_family_table_disagreeing_with_the_code_registry_is_reported(
        self,
    ) -> None:
        """The table is what an author edits, the dict is what checks read.

        Step 4 of the procedure adds a row to section 11.1, and every check in
        the project reads ``_EVALUATION_FAMILIES``. A family in one and not the
        other leaves the scope statement describing less than the suite
        exercises, which section 11.3 records as the reason this is a registry
        rather than a list.

        **The fourth instance of one shape in this module**, after ``112202``,
        ``112313`` and ``112314``: a document restates a fact that lives
        elsewhere, and the restatement rots.

        Returns:
            None
        """
        taxonomy = (
            Path(__file__).resolve().parents[2]
            / "docs" / "design" / "harness_test_taxonomy.md"
        )
        # BOUNDED TO SECTION 11.1, because that is the table the procedure
        # names and the registry is open: a sixth family is expected (section
        # 11.6), and an unbounded scan makes any four-column table in this
        # document a family the moment its first cell is a backticked
        # lowercase token. This read the whole file until 2026-10-03.
        tabled: set[str] = set()
        for line in section_lines(taxonomy, "### 11.1"):
            match = _FAMILY_ROW.match(line.strip())
            if match is not None:
                tabled.add(match.group("identifier"))

        registered = set(registered_evaluation_families())

        assert tabled, "section 11.1 states no families, so the table was not found"
        assert tabled == registered, (
            "section 11.1 and _EVALUATION_FAMILIES disagree; "
            f"tabled only: {sorted(tabled - registered)}, "
            f"registered only: {sorted(registered - tabled)}"
        )

    def MQC_CMN_UNI_112229_every_requirement_in_the_matrix_appears_in_the_plan(
        self,
    ) -> None:
        """A requirement traced and unstated means the plan understates itself.

        The harness test plan states the requirements and ``rtm_harness.csv``
        traces them to cases. Twelve requirements were in the matrix and absent
        from the plan, all added over one working session, and nothing compared
        the two.

        **The fifth instance of one shape in this module**, after ``112202``,
        ``112313``, ``112314`` and ``112228``: two artefacts state one fact and
        nothing compares them.

        Returns:
            None
        """
        root = Path(__file__).resolve().parents[2]
        plan = (root / "docs" / "testing" / "harness_test_plan.md").read_text(
            encoding="utf-8"
        )
        stated = set(_REQUIREMENT_ID.findall(plan))

        with (root / "docs" / "testing" / "rtm_harness.csv").open(
            encoding="utf-8-sig", newline=""
        ) as handle:
            traced = {
                row["requirement_id"]
                for row in csv.DictReader(handle)
                if row["requirement_id"].startswith("MQC_REQ_HAR_")
            }

        assert stated and traced, "one of the two artefacts was not read"
        assert not traced - stated, (
            "these requirements are traced and never stated, so the plan "
            f"understates what the harness guarantees: {sorted(traced - stated)}"
        )
        assert not stated - traced, (
            "these requirements are stated and never traced, so nothing covers "
            f"them: {sorted(stated - traced)}"
        )

    def MQC_CMN_UNI_112230_a_registered_family_without_ground_truth_is_reported(
        self,
    ) -> None:
        """Step 2 refuses a family gradable only by rubric.

        That refusal is the reason all registered families exist: a family
        measured by a judge alone adds cases without adding confidence, because
        it measures the judge as much as the candidate.

        **The criterion held only while an author remembered it.** A registered
        family carrying no ground-truth mechanism means step 2 was skipped, and
        nothing said so.

        Returns:
            None
        """
        registered = registered_evaluation_families()
        assert registered, "the registry is empty, so nothing is being checked"

        for identifier in sorted(registered):
            family = evaluation_family(identifier)
            assert family is not None, f"{identifier} is listed and not resolvable"
            assert family.ground_truth.strip(), (
                f"{identifier} declares no ground-truth mechanism, so step 2 of "
                f"the procedure was skipped and the admission criterion was not "
                f"applied"
            )
            assert family.input_shape.strip(), (
                f"{identifier} declares no input shape, so a reader cannot tell "
                f"what the model receives"
            )


class TestMQCInventoryIdentifiers:
    """An identifier is assigned once and never rebound."""

    def MQC_CMN_UNI_112226_an_identifier_appearing_twice_in_one_inventory_is_reported(
        self,
    ) -> None:
        """An identifier is assigned once and never rebound.

        **Every per-row check passed while an identifier was bound twice**,
        because each was keyed on a row and the defect was a relationship
        between two rows. `112303` found both rows, `112305` found both names
        valid, `112306` matched the first, and `112203` saw a row count that had
        genuinely grown.

        That is the shape a per-row check cannot see, whatever its strictness.

        Returns:
            None
        """
        design_dir = Path(__file__).resolve().parents[2] / "docs" / "design"
        seen: dict[str, list[str]] = {}

        for document in sorted(design_dir.glob("*.md")):
            if document.name in _HISTORICAL_DOCUMENTS:
                continue
            for line in document.read_text(encoding="utf-8").splitlines():
                match = _INVENTORY_ROW.match(line.strip())
                if match is None:
                    continue
                identifier = match.group("identifier")
                behaviour = match.group("behaviour")
                seen.setdefault(f"{document.name}:{identifier}", []).append(behaviour)

        duplicated = {
            where: names for where, names in seen.items() if len(names) > 1
        }
        assert not duplicated, (
            "an identifier is assigned once and never reused, so two live rows "
            "for one identifier rebind it to different behaviour: "
            + "; ".join(
                f"{where} bound to {' and '.join(names)}"
                for where, names in sorted(duplicated.items())
            )
        )
