# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: Apache-2.0
"""The block naming the cases a test module holds, generated and compared.

Specified in ``.claude/rules/testing-standards.md``, "A Test Module Lists The
Cases It Holds".

**Derived data, so it is generated rather than written.** A module docstring
says what a module is about and not what is in it, and a list a human maintains
is one more restatement to drift: the project has already shipped a README
claiming 498 cases against 462 inventoried.

**Parsed, not matched.** A regex cannot tell a definition from a definition
inside a string literal, which this project corrected once already when five
case doubles inside a triple-quoted suite read as untraced cases.
"""

import ast
import logging
from pathlib import Path
from typing import Final, NamedTuple, Optional

logger = logging.getLogger(__name__)

_OPEN: Final[str] = "# " + "-" * 61 + " cases in here"
_CLOSE: Final[str] = "# " + "-" * 60 + " end of cases"
_CREDIT: Final[str] = "# Generated by `tools/refresh_case_summaries.py`."

# A case callable, by the prefix every test artifact carries without exception
# (`testing-standards.md` section 1).
_PREFIX: Final[str] = "MQC_"

_SKIP_PARTS: Final[frozenset[str]] = frozenset({
    "__pycache__", "build", ".venv", ".git", "node_modules",
})


class CaseEntry(NamedTuple):
    """One case a module defines.

    Attributes:
        holder (str): The class it sits in.
        identifier (str): Its six digits.
        behaviour (str): The behaviour suffix.
    """

    holder: str
    identifier: str
    behaviour: str


def case_modules(root: Path) -> list[Path]:
    """Return every collected test module beneath a root.

    Args:
        root (Path): The repository root.

    Returns:
        list[Path]: Each ``mqc_*.py`` under ``tests``, sorted, excluding
        generated trees. **A support module is included and yields no cases**,
        which is what lets the check report a stale block in one.
    """
    base = root / "tests"
    if not base.is_dir():
        return []
    return sorted(
        path for path in base.rglob("mqc_*.py")
        if not _SKIP_PARTS & set(path.parts)
    )


def cases_in(path: Path) -> list[CaseEntry]:
    """Return every case a module defines, in source order.

    **Source order rather than sorted**, so the block reads as a table of
    contents for the file in front of the reader.

    Args:
        path (Path): The module.

    Returns:
        list[CaseEntry]: One entry per case callable, empty for a module that
        defines none.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    found: list[CaseEntry] = []
    for holder in tree.body:
        if not isinstance(holder, ast.ClassDef):
            continue
        for node in holder.body:
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if not node.name.startswith(_PREFIX):
                continue
            parsed = _split(node.name)
            if parsed is None:
                logger.warning(
                    "%s defines %s, which is not a case identifier",
                    path.name, node.name,
                )
                continue
            identifier, behaviour = parsed
            found.append(CaseEntry(holder.name, identifier, behaviour))
    return found


def _split(name: str) -> Optional[tuple[str, str]]:
    """Return a callable's identifier and behaviour suffix.

    Args:
        name (str): The callable's name.

    Returns:
        Optional[tuple]: The digits and the suffix, or None where the name does
        not follow ``MQC_<MODULE>_<LAYER>_<DIGITS>_<behaviour>``.
    """
    parts = name.split("_")
    if len(parts) < 5 or not parts[3].isdigit():
        return None
    return parts[3], "_".join(parts[4:])


def summary_block(entries: list[CaseEntry]) -> str:
    """Return the block a module holding these cases should carry.

    Args:
        entries (list[CaseEntry]): The module's cases, in source order.

    Returns:
        str: The block, newline terminated, or an empty string where the module
        defines no case. **An empty string rather than an empty block**, so a
        support module carries nothing rather than a heading over nothing.
    """
    if not entries:
        return ""
    lines = [_OPEN, _CREDIT, "#"]
    holder = ""
    for entry in entries:
        if entry.holder != holder:
            holder = entry.holder
            lines.append(f"# {holder}")
        lines.append(f"#   {entry.identifier}  {entry.behaviour}")
    lines.append(_CLOSE)
    return "\n".join(lines) + "\n"


def existing_block(text: str) -> str:
    """Return the block a module already carries.

    Args:
        text (str): The module's source.

    Returns:
        str: The block including its delimiters, or an empty string where the
        module carries none.
    """
    start = text.find(_OPEN)
    if start < 0:
        return ""
    end = text.find(_CLOSE, start)
    if end < 0:
        return ""
    return text[start:end + len(_CLOSE)] + "\n"


def refreshed_source(path: Path) -> str:
    """Return the module's source with its block correct.

    **Inserted after the docstring and before the imports**, which is where a
    reader looks and where no tool has to touch authored prose.

    Args:
        path (Path): The module.

    Returns:
        str: The source to write. Identical to what is there when the block is
        already correct, so the tool is safe to run repeatedly.

    Raises:
        ValueError: With ``QC_HARNESS_PARSER_ERROR`` when the module has no
            docstring to insert after. Guessing a position would put the block
            above the SPDX header or inside the licence tag.
    """
    text = path.read_text(encoding="utf-8")
    wanted = summary_block(cases_in(path))
    present = existing_block(text)

    if present:
        return text.replace(present, wanted, 1) if wanted else text.replace(
            present + "\n", "", 1
        ).replace(present, "", 1)
    if not wanted:
        return text

    tree = ast.parse(text)
    docstring = ast.get_docstring(tree)
    if docstring is None or not tree.body:
        raise ValueError(
            f"QC_HARNESS_PARSER_ERROR: {path.name} has no module docstring, so "
            f"there is no position for its case block"
        )
    lines = text.splitlines(keepends=True)
    after = tree.body[0].end_lineno
    return "".join(lines[:after]) + "\n" + wanted + "".join(lines[after:])


def summary_problems(root: Path) -> list[str]:
    """Report every test module whose block disagrees with its own cases.

    **Neither direction can be fixed by editing the block.** A case added
    without refreshing fails here, and a block naming a deleted case fails here
    too; the remedy for both is one command.

    Args:
        root (Path): The repository root.

    Returns:
        list[str]: One entry per module, naming what disagrees. An empty list
        means every block matches the module it sits in.
    """
    problems: list[str] = []
    for path in case_modules(root):
        text = path.read_text(encoding="utf-8")
        wanted = summary_block(cases_in(path))
        present = existing_block(text)
        relative = path.relative_to(root).as_posix()
        if wanted and not present:
            problems.append(
                f"{relative} defines cases and carries no case block; run "
                f"tools/refresh_case_summaries.py"
            )
        elif present and not wanted:
            problems.append(
                f"{relative} carries a case block and defines no case, so the "
                f"block names what is not there"
            )
        elif present.strip() != wanted.strip():
            problems.append(
                f"{relative} carries a case block that disagrees with the "
                f"cases it defines; run tools/refresh_case_summaries.py"
            )
    if problems:
        logger.warning("%d case block(s) disagree with their module", len(problems))
    return problems


def block_delimiters() -> tuple[str, str]:
    """Return the block's opening and closing lines.

    Returns:
        tuple[str, str]: The two delimiters, so a case asserts the shape the
        tool writes rather than a copy of it.
    """
    return _OPEN, _CLOSE
