# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: Apache-2.0
"""The pytest hooks every repository running MQC cases needs.

Extracted 2026-09-23, when the split made a second ``conftest.py`` necessary.

**A consumer's suite is invoked with the same flags as ours.** ``--mode
replay`` is in the fan-out command in ``config/consumers.yaml``, and a flag
pytest has not been told about is an argument error before a single test runs.
A case repository therefore has to register the option registry exactly as this
one does.

**Two conftest files registering the same flags would drift**, and the symptom
would be a report contradicting the run it describes: a consumer accepting a
value we reject, or defaulting a flag differently and attributing the
difference to the model. ``cmn_verdict_and_cli.md`` section 7.1 already names
two surfaces for the option registry, the pytest parser and the standalone
verdict tool, and neither states a flag twice. A consumer is a third caller of
the first surface, not a second definition of it.

The consumer's ``conftest.py`` is therefore a delegation:

.. code-block:: python

    from cmn.pytest_support import (
        add_mqc_options, configure_invocation, label_priority_severity,
        select_priority_bands,
    )

    def pytest_addoption(parser): add_mqc_options(parser)
    def pytest_configure(config): configure_invocation(config)
    def pytest_runtest_setup(item): enforce_dependencies(item)
    def pytest_collection_modifyitems(config, items):
        label_priority_severity(items)
        select_priority_bands(config, items)
        arrange_dependencies(items)

    @pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_makereport(item, call):
        record_from_report(item, (yield).get_result())

**Fixtures are deliberately not here.** The harness fixtures build
:class:`~ingestion.schemas.EvaluationCase` records from sample payloads, which
is harness test scaffolding rather than a capability a case repository
consumes. Exporting them would put harness-internal shapes into a consumer's
namespace and invite a case to assert against one.
"""

import logging
import re
from typing import Any, Final, Optional

import pytest

from cmn.options import Option, build_invocation, registered_options

logger = logging.getLogger(__name__)

# P0 blocks, P4 is trivial. The mapping is the one place the two vocabularies
# meet, and it is here rather than in a conftest so a consumer cannot hold a
# different opinion about what P2 means.
_SEVERITY_BY_PRIORITY: dict[int, str] = {
    0: "blocker",
    1: "critical",
    2: "normal",
    3: "minor",
    4: "trivial",
}


def _add_pytest_option(group: Any, declared: Option) -> None:
    """Add one declared option to a pytest parser group.

    Args:
        group (Any): The option group.
        declared (Option): Its registration.

    Returns:
        None
    """
    if declared.is_flag:
        group.addoption(
            declared.cli_flag, action="store_true", default=declared.default,
            help=declared.help_text,
        )
        return
    group.addoption(
        declared.cli_flag,
        # Declared on every enumerated flag, so a typo fails at parse time with
        # the valid values listed rather than deep inside a run that has already
        # spent quota.
        choices=list(declared.choices) if declared.choices else None,
        default=declared.default,
        help=declared.help_text,
    )


def add_mqc_options(parser: Any) -> None:
    """Declare the execution flags from the shared option registry.

    **The first of the two surfaces** (``cmn_verdict_and_cli.md`` section 7.1).
    The standalone verdict tool builds its ``argparse`` parser from the same
    registry, so a flag cannot exist on one surface and not the other, and
    neither can accept a value the other rejects.

    ``pytest_addoption`` is argparse-backed, so these gain autogenerated help
    through ``pytest --help`` without a second parser competing for
    ``sys.argv``.

    Args:
        parser (Any): pytest's parser.

    Returns:
        None
    """
    group = parser.getgroup("mqc", "AP-Model-QC execution options")
    for declared in registered_options():
        _add_pytest_option(group, declared)



def _flags_named(config: Any) -> frozenset[str]:
    """Return the flags the caller actually wrote, however they wrote them.

    **Comparing a value against its default cannot answer this.** Choosing the
    default explicitly and choosing nothing produce the same value, so
    `--engine gemini` read as an unchosen provider and every deliberate run
    carried `QC_DATA_ENGINE_DEFAULTED`. A warning that fires when the thing it
    warns about did not happen is worse than no warning: it teaches the reader
    to skip the line.

    **Both spellings count.** pytest accepts `--engine gemini` and
    `--engine=gemini`, and a reader choosing the second did not choose less.

    Args:
        config (Any): pytest's configuration, carrying the raw invocation.

    Returns:
        frozenset[str]: Every flag present on the command line, including its
        leading dashes. **Empty where the invocation is unavailable**, which
        falls back to the value comparison rather than raising: a warning is not
        worth failing a run over.
    """
    params = getattr(config, "invocation_params", None)
    arguments = list(getattr(params, "args", ()) or ())
    return frozenset(
        argument.split("=", 1)[0]
        for argument in arguments
        if isinstance(argument, str) and argument.startswith("-")
    )


def configure_invocation(config: Any) -> None:
    """Record what the run was invoked with, and warn on a defaulted engine.

    **Every flag that can change a result is recorded**, and a defaulted engine
    emits a warning into the artifact so a cloned repository running
    unconfigured produces a record saying so (A7.4).

    Args:
        config (Any): pytest's configuration.

    Returns:
        None
    """
    named = _flags_named(config)
    supplied = {
        declared.metadata_key: config.getoption(declared.metadata_key)
        for declared in registered_options()
        if declared.cli_flag in named
        or config.getoption(declared.metadata_key, None) not in (None, declared.default)
    }
    invocation = build_invocation(supplied)
    config.mqc_invocation = invocation
    for warning in invocation.warnings:
        logger.warning("%s", warning)


def label_priority_severity(items: list[pytest.Item]) -> None:
    """Translate the priority marker into an Allure severity label.

    **One source of truth, two consumers.** The run-verdict gate reads the
    marker and downstream analysis reads the label. Maintaining the label by
    hand would give two places to state one fact.

    **A precondition carries no priority and therefore no severity.** The hook
    leaves it unset rather than inventing a default, because a default would
    make preconditions sortable by a severity nobody assigned
    (``framework-rules.md`` section 3.3).

    Args:
        items (list): The collected test items.

    Returns:
        None
    """
    for item in items:
        marker = item.get_closest_marker("priority")
        if marker is None:
            continue
        level = int(marker.args[0])
        severity = _SEVERITY_BY_PRIORITY.get(level)
        if severity is None:
            logger.warning(
                "Test %s carries priority %d, which is not 0 to 4", item.name, level
            )
            continue
        item.add_marker(pytest.mark.allure_label(severity, label_type="severity"))


# THE CASCADE'S MEMORY, keyed by the five-digit identifier of a base case.
# Module level because pytest hooks are free functions and the two halves of
# the cascade run in different hooks: one records, the other reads.
_BASE_OUTCOMES: dict[str, bool] = {}

_UNMET: Final[str] = "QC_HARNESS_DEPENDENCY_UNMET"

# Identifiers look like MQC_<MODULE>_<LAYER>_<5 digits>_<behaviour>.
_IDENTIFIER = re.compile(r"MQC_[A-Z]+_[A-Z]{3,5}_(\d{5})_")


def case_identifier(name: str) -> Optional[str]:
    """Return the five-digit identifier a test name carries.

    Args:
        name (str): The test callable's name.

    Returns:
        Optional[str]: The identifier, or ``None`` for a name that carries
        none. **Identifiers are the only stable handle in the suite**: a
        behaviour suffix changes when the behaviour is reworded, and a
        dependency that breaks on a rename is one nobody maintains.
    """
    matched = _IDENTIFIER.search(name)
    return matched.group(1) if matched else None


def reset_dependency_state() -> None:
    """Forget every recorded base outcome.

    Returns:
        None: Used between runs in the same process, which is what a test of
        the cascade itself needs.
    """
    _BASE_OUTCOMES.clear()


def record_base_outcome(item: pytest.Item, passed: bool) -> None:
    """Record whether a foundational case held.

    **A foundation that did not run did not hold.** A base case skipped during
    setup, because its own dependency failed, produces no measurement, so its
    dependents must skip rather than error. Recording only the call phase left
    a chain reporting an unmet dependency as a hard error two links down.

    Args:
        item (pytest.Item): The test that ran.
        passed (bool): Whether it passed. False for a skip, which is the
            distinction a chain depends on.

    Returns:
        None
    """
    if item.get_closest_marker("base") is None:
        return
    identifier = case_identifier(item.name)
    if identifier is None:
        logger.warning(
            "%s is marked base and carries no identifier, so nothing can "
            "depend on it", item.name,
        )
        return
    _BASE_OUTCOMES[identifier] = passed



def record_from_report(item: pytest.Item, report: Any) -> None:
    """Record a foundational outcome from whichever phase reported it.

    **The outcome decides, not the phase**, which is the distinction the
    calling hooks previously got wrong by recording only ``call``.

    A middle link in a chain is both a foundation and a dependent: when its own
    dependency does not hold, :func:`enforce_dependencies` skips it from
    ``pytest_runtest_setup``, and that skip is reported with ``when ==
    "setup"``. Recording only the call phase left **no entry at all** for it, so
    the next link found an unknown identifier and hard-failed, reporting "no
    collected case declares this as base" about a case that was collected and
    marked base (design section 10.28.5).

    Args:
        item (pytest.Item): The test that ran.
        report (Any): The phase report pytest produced.

    Returns:
        None: A ``setup`` skip or error records ``False``, because a case that
        did not reach its call phase is a foundation that did not hold. **Only
        the call phase can record a pass**, since nothing earlier has measured
        anything.
    """
    if report.when == "call":
        record_base_outcome(item, report.passed)
    elif report.when == "setup" and not report.passed:
        record_base_outcome(item, False)

def declared_dependencies(item: pytest.Item) -> list[str]:
    """Return the identifiers a test declares it depends on.

    Args:
        item (pytest.Item): The collected test.

    Returns:
        list[str]: The five-digit identifiers, empty when it declares none.
    """
    declared: list[str] = []
    for marker in item.iter_markers(name="depends_on"):
        declared.extend(str(argument) for argument in marker.args)
    return declared



def declared_bases(items: list[pytest.Item]) -> dict[str, list[pytest.Item]]:
    """Return the collected foundational cases, by identifier.

    Args:
        items (list): The collected test items.

    Returns:
        dict[str, list]: Identifier to the items declaring it. **A list rather
        than one item**, because a parametrized foundation is several items
        under one identifier and every one of them has to hold.
    """
    bases: dict[str, list[pytest.Item]] = {}
    for item in items:
        if item.get_closest_marker("base") is None:
            continue
        identifier = case_identifier(item.name)
        if identifier is None:
            logger.warning(
                "%s is marked base and carries no identifier, so nothing can "
                "depend on it", item.name,
            )
            continue
        bases.setdefault(identifier, []).append(item)
    return bases


def unknown_dependencies(items: list[pytest.Item]) -> list[str]:
    """Return every dependency naming an identifier nothing declares as base.

    **Asked at collection because that is where it has an answer.** At setup an
    absent identifier means either that nothing declares it or that its base
    has not run yet, and those are unrelated situations that reached one branch
    (design section 10.28.6).

    Args:
        items (list): The collected test items.

    Returns:
        list[str]: One message per offender, in collection order, empty when
        every dependency resolves.
    """
    bases = declared_bases(items)
    return [
        f"{item.name} depends on {identifier}, which no collected case "
        f"declares as base"
        for item in items
        for identifier in declared_dependencies(item)
        if identifier not in bases
    ]


def order_by_dependency(items: list[pytest.Item]) -> list[pytest.Item]:
    """Return the items with every foundation ahead of its dependents.

    **A depth-first post-order walk**, which is a topological sort that
    preserves the incoming order wherever it does not have to change it.
    Randomisation is a feature of this suite, so the cascade takes exactly as
    much order as it needs and independent cases stay shuffled.

    Args:
        items (list): The collected test items, in whatever order collection
            and ``pytest-randomly`` produced.

    Returns:
        list[pytest.Item]: The same items, reordered.

    Raises:
        ValueError: With ``QC_HARNESS_DEPENDENCY_UNMET`` naming a cycle. **Two
            cases each declaring the other foundational is a design error in
            the cases**, and silently picking one to run first would let it
            survive.
    """
    bases = declared_bases(items)
    ordered: list[pytest.Item] = []
    settled: set[int] = set()

    def visit(item: pytest.Item, walking: list[pytest.Item]) -> None:
        """Emit one item after everything it depends on.

        Args:
            item (pytest.Item): The item to place.
            walking (list): The current path, for cycle reporting.

        Returns:
            None

        Raises:
            ValueError: When the path revisits an item.
        """
        if id(item) in settled:
            return
        if any(id(seen) == id(item) for seen in walking):
            names = " -> ".join(seen.name for seen in walking + [item])
            raise ValueError(
                f"QC_HARNESS_DEPENDENCY_UNMET: foundational cases form a "
                f"cycle, so no order satisfies them: {names}"
            )
        walking.append(item)
        for identifier in declared_dependencies(item):
            for foundation in bases.get(identifier, ()):
                visit(foundation, walking)
        walking.pop()
        settled.add(id(item))
        ordered.append(item)

    for item in items:
        visit(item, [])
    return ordered


def selected_bands(raw: str) -> frozenset[int]:
    """Return the priority bands a run asked for.

    Args:
        raw (str): The comma-separated value of ``--priority``, empty for all.

    Returns:
        frozenset[int]: The bands, empty when none was named.

    Raises:
        ValueError: With ``QC_HARNESS_PARSER_ERROR`` when a band is not 0 to 4.
            **Refused rather than ignored**, because a typo that silently
            selected everything would report a full run as a band.
    """
    if not raw or not raw.strip():
        return frozenset()
    bands: set[int] = set()
    for piece in raw.split(","):
        text = piece.strip()
        if not text:
            continue
        if not text.isdigit() or int(text) not in _SEVERITY_BY_PRIORITY:
            raise ValueError(
                f"QC_HARNESS_PARSER_ERROR: priority band {text!r} is not 0 to 4"
            )
        bands.add(int(text))
    return frozenset(bands)


def item_priority(item: pytest.Item) -> Optional[int]:
    """Return the priority a test declares, or None.

    Args:
        item (pytest.Item): The collected test.

    Returns:
        Optional[int]: The band, absent on a precondition which carries none.
    """
    marker = item.get_closest_marker("priority")
    if marker is None or not marker.args:
        return None
    try:
        return int(marker.args[0])
    except (TypeError, ValueError):
        return None


def _closure(chosen: list[pytest.Item], items: list[pytest.Item]) -> set[str]:
    """Return every identifier the chosen items rest on, transitively.

    Args:
        chosen (list): The items the band selected.
        items (list): Everything collected, to resolve bases against.

    Returns:
        set[str]: The identifiers needed as foundations.
    """
    by_identifier = declared_bases(items)
    needed: set[str] = set()
    frontier = list(chosen)
    while frontier:
        current = frontier.pop()
        for identifier in declared_dependencies(current):
            if identifier in needed:
                continue
            needed.add(identifier)
            frontier.extend(by_identifier.get(identifier, []))
    return needed


def select_priority_bands(config: pytest.Config, items: list[pytest.Item]) -> None:
    """Deselect every graded case outside the requested bands.

    **Preconditions are never deselected.** They carry no priority and they are
    what establishes that the corpus is loadable at all, so a band run that
    dropped them would measure against an unchecked corpus.

    **A band takes its foundations with it.** A dependent whose base is absent
    makes the suite unresolvable, so the closure runs too and gates its
    dependents as it would in a full run. It is not part of what the band
    reports; it is what makes the band runnable alone, which is the whole point
    of selecting one.

    Args:
        config (pytest.Config): pytest's configuration, read for ``--priority``.
        items (list): The collected items, filtered in place.

    Returns:
        None
    """
    bands = selected_bands(str(config.getoption("--priority") or ""))
    if not bands:
        return

    graded = sum(1 for item in items if item_priority(item) is not None)
    chosen = [item for item in items if item_priority(item) in bands]
    needed = _closure(chosen, items)

    keep, drop, foundations = [], [], []
    for item in items:
        priority = item_priority(item)
        if priority is None or priority in bands:
            keep.append(item)
        # A FOUNDATION OF THE BAND, kept so the band can run at all, and
        # IDENTIFIED THE WAY `declared_bases` DOES rather than by substring:
        # two conventions for what a case is called would eventually disagree
        # about which foundations a band needs, and `30015` is a substring of
        # `130015`.
        elif case_identifier(item.name) in needed:
            foundations.append(item)
            keep.append(item)
        else:
            drop.append(item)

    if drop:
        config.hook.pytest_deselected(items=drop)
        items[:] = keep
    # THE BAND IS WHAT WAS CHOSEN, not what survived. A foundation kept for the
    # band is graded and out of band, so reporting the kept set as the band
    # would overstate what this run measured.
    logger.info(
        "priority bands %s selected %d graded case(s) of %d, keeping %d foundation(s)",
        ",".join(str(band) for band in sorted(bands)),
        len(chosen), graded, len(foundations),
    )


def arrange_dependencies(items: list[pytest.Item]) -> None:
    """Reorder the collected items in place, refusing an unresolvable suite.

    Args:
        items (list): The collected test items, replaced in place because that
            is the contract ``pytest_collection_modifyitems`` has with pytest.

    Returns:
        None

    Raises:
        ValueError: With ``QC_HARNESS_DEPENDENCY_UNMET`` when a dependency
            names no collected base, or when the declarations form a cycle.
            **Reported once, naming every offender**, rather than erroring per
            dependent at setup.
    """
    unknown = unknown_dependencies(items)
    if unknown:
        raise ValueError(
            "QC_HARNESS_DEPENDENCY_UNMET: a dependency on a case that does "
            "not exist is satisfied by nothing existing to fail; "
            + "; ".join(unknown)
        )
    items[:] = order_by_dependency(items)

def enforce_dependencies(item: pytest.Item) -> None:
    """Skip a test whose foundation did not hold.

    **Skipped, never failed.** A dependent that did not run produced no
    measurement, and recording a failure would assert something about a model
    nobody asked. The reason is ``dependency``, which the verdict already
    excludes from the skip denominator so one foundational failure does not
    also breach the skip ceiling.

    Args:
        item (pytest.Item): The test about to run.

    Returns:
        None

    **Only the outcome is decided here.** Whether the identifier exists at all
    is a question about the collected population, which `arrange_dependencies`
    answers at collection where the population is known.
    """
    for identifier in declared_dependencies(item):
        # ABSENT MEANS DID NOT RUN, WHICH IS DID NOT HOLD. The other reading,
        # that nothing declares this identifier, is settled at collection by
        # `arrange_dependencies`, which also orders every base ahead of its
        # dependents. Asking here could not tell the two apart, and reported
        # an ordering accident as a missing case (design section 10.28.6).
        if not _BASE_OUTCOMES.get(identifier, False):
            logger.warning(
                "%s %s did not hold, so %s was not executed",
                _UNMET, identifier, item.name,
            )
            pytest.skip(f"{_UNMET}: foundational case {identifier} did not hold")
